import { parse } from 'csv-parse/sync'
import * as XLSX from 'xlsx'
import type { Order } from './types.js'

const aliases: Record<keyof Order,string[]> = { orderId:['order id','orderid','order number'],orderDate:['order date','created at','date'],channel:['channel','sales channel'],product:['product','product name','item'],sku:['sku','product sku'],quantity:['quantity','qty'],revenue:['revenue','selling price','order value','amount'],productCost:['product cost','cost'],shippingCost:['shipping cost','shipping'],fees:['fees','platform fee'],paymentMethod:['payment method','payment mode'],status:['status','order status'],state:['state'],city:['city'],rto:['rto'],return:['return','returned'],profit:['profit','net profit'],profitMargin:['profit margin','margin'] }
const clean=(s:string)=>s.trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ')
const number=(v:unknown)=>{ if(v===undefined||v===null||v==='') return null; const n=Number(String(v).replace(/[,₹$%]/g,'')); return Number.isFinite(n)?n:null }
const bool=(v:unknown)=>v==null||v===''?null:/^(true|yes|y|1)$/i.test(String(v))
export function normalize(rows: Record<string,unknown>[]) { const keys=Object.keys(rows[0]??{}); const map: Partial<Record<keyof Order,string>>={}; for(const field of Object.keys(aliases) as (keyof Order)[]) { const hit=keys.find(k=>aliases[field].includes(clean(k))); if(hit) map[field]=hit }
 return { orders: rows.map(row=>{ const get=(f:keyof Order)=>map[f]?row[map[f] as string]:undefined; return { orderId:get('orderId')?.toString()??null,orderDate:get('orderDate')?.toString()??null,channel:get('channel')?.toString()??null,product:get('product')?.toString()??null,sku:get('sku')?.toString()??null,quantity:number(get('quantity')),revenue:number(get('revenue')),productCost:number(get('productCost')),shippingCost:number(get('shippingCost')),fees:number(get('fees')),paymentMethod:get('paymentMethod')?.toString()??null,status:get('status')?.toString()??null,state:get('state')?.toString()??null,city:get('city')?.toString()??null,rto:bool(get('rto')),return:bool(get('return')),profit:number(get('profit')),profitMargin:number(get('profitMargin')) } }), mappedColumns:Object.values(map).filter(Boolean) as string[], unmappedColumns:keys.filter(k=>!Object.values(map).includes(k)), detectedColumns:keys }
}
export function parseFile(filename:string, buffer:Buffer) { const ext=filename.toLowerCase().split('.').pop(); const workbook=ext==='xlsx'||ext==='xls'?XLSX.read(buffer,{type:'buffer'}):null; const rows=workbook?XLSX.utils.sheet_to_json<Record<string,unknown>>(workbook.Sheets[workbook.SheetNames[0]],{defval:null}):parse(buffer.toString('utf8'),{columns:true,skip_empty_lines:true,relax_column_count:true}) as Record<string,unknown>[]; return normalize(rows) }
